name: store_ify
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # For in-app localization
  easy_localization: ^3.0.7
  # A declarative routing solution for navigation
  auto_route: ^9.2.2
  # Networking
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  # Dio interceptor that logs network calls in a pretty, easy to read format.
  pretty_dio_logger: ^1.3.1
  # State management
  flutter_bloc: ^8.1.6
  # Code generator (mainly used with Cubit & retrofit)
  freezed_annotation: ^2.4.1
  # Classes and helper functions that support JSON code generation via the `json_serializable` package.
  json_annotation: ^4.9.0
  # An SVG rendering and widget library for Flutter, which allows painting
  flutter_svg: ^2.0.10+1
  # Simple direct Service Locator that allows to access the concrete implementation from everywhere
  get_it: ^7.7.0
  # (OTP) text field
  pinput: ^5.0.0
  # Flutter plugin for reading and writing simple key-value pairs for cache
  shared_preferences: ^2.2.3
  # Provides API to store data in secure storage
  flutter_secure_storage: ^9.2.2
  # A flutter plugin for adapting screen and font size.Guaranteed to look good on different models
  flutter_screenutil: ^5.9.3
  # Customizable rating bar for flutter
  flutter_rating_bar: ^4.0.1
  # For native splash screen
  flutter_native_splash: ^2.4.0
  # To add staggered animations to your ListView, GridView
  flutter_staggered_animations: ^1.1.1
  # To load and cache network images
  cached_network_image: ^3.3.1
  # Customizable animated page indicator with a set of built-in effects.
  smooth_page_indicator: ^1.2.0+3
  # A PageView widget adjusting it's height to currently displayed page
  expandable_page_view: ^1.0.17
  # Allows user to choose numbers by scrolling spinners
  numberpicker: ^2.1.2
  # Provides a cross-platform (iOS, Android) API for generic location (GPS etc.) functions.
  geolocator: ^13.0.1
  # Provides easy geocoding and reverse-geocoding features
  geocoding: ^3.0.0
  # A customized Flutter TextFormField to input international phone number along with country code
  intl_phone_field: ^3.2.0
  # For Beautiful animations 
  animate_do: ^3.3.4
  # For formatting numbers and dates
  intl: ^0.19.0
  # For caching data in local storage 
  hive_flutter: ^1.1.0
  # To get App directory
  path_provider: ^2.1.4
  # An easy way to add shimmer effect
  shimmer: ^3.0.0
  # Used for picking images
  image_picker: ^1.1.2
  # Used for compressing images
  flutter_image_compress: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Updating app's launcher icon.
  flutter_launcher_icons: ^0.13.1
  # Code generator (mainly used with Cubit & retrofit)
  retrofit_generator: ^9.1.2
  # Automatically generate navigation
  auto_route_generator: ^9.0.0
  # A build system for Dart code generation and modular compilation.
  build_runner: ^2.4.12
  # Recommended lints to encourage good coding practices
  flutter_lints: ^4.0.0
  # Code generator (mainly used with Cubit & retrofit)
  freezed: ^2.5.2
  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^6.8.0
  # Performs static analysis of Dart code. It is useful for tool integration and embedding.
  analyzer: ^6.7.0
  # For generating Hive type adapters
  hive_generator: ^2.0.1


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/translations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 900

flutter_assets:
  assets_path: assets/
  output_path: lib/core/utils/
  filename: app_assets.dart
  field_prefix: null

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
